services:
  server:
    container_name: server
    build:
      context: ./server
      target: builder
    stop_signal: SIGINT
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes: ["./server:/server"]
    ports:
      - "8080:8080"
